In [15]:
# NumPy: dasar-dasar untuk pemula
# Menginstall NumPy
# conda install numpy
# atau 
# pip install numpy

# Bagaimana cara mengimpor NumPy

import numpy as py

# Membaca Kode contoh
a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [16]:
import numpy as np
#Salah satu cara kita menginisialisasi array NumPy adalah dari daftar Python, menggunakan daftar bersarang untuk
# data dua dimensi atau lebih tinggi.
# Misalnya:
a = np.array([1, 2, 3, 4, 5, 6])
# atau
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[0])

[1 2 3 4]


In [22]:
# cara membuat array dasar
# Bagian ini mencakup np.array(), np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace(), dtype
import numpy as np
a = np.array([1, 2, 3])
#Selain membuat array dari rangkaian elemen, Anda dapat dengan mudah membuat array terisi dengan 0
print(np.zeros(2))

#Atau array yang diisi dengan 1:
print(np.ones(2))

# Atau bahkan array kosong! Fungsi kosong membuat array yang konten awalnya acak dan bergantung pada keadaan
# memori. Alasan menggunakan kosong di atas nol (atau yang serupa) adalah kecepatan - pastikan untuk mengisi setiap
# elemen setelahnya!

print(np.empty(2))

#Anda dapat membuat array dengan berbagai elemen:
print(np.arange(4))

#Dan bahkan array yang berisi rentang interval yang berjarak sama. Untuk melakukan ini, Anda akan menentukan
# angka pertama, angka terakhir, dan ukuran langkah.

print(np.arange(2, 9, 2))

#Anda juga dapat menggunakan np.linspace() untuk membuat array dengan nilai yang diberi jarak linier dalam interval
# tertentu:
print(np.linspace(0, 10, num=5))




[0. 0.]
[1. 1.]
[1. 1.]
[0 1 2 3]
[2 4 6 8]
[ 0.   2.5  5.   7.5 10. ]


In [31]:
#Menentukan tipe data anda
#Meskipun tipe data defaultnya adalah floating point (np.float64), Anda dapat secara eksplisit menentukan tipe data
# mana yang Anda inginkan menggunakan kata kunci dtype .

x = np.ones(2, dtype=np.int64)
x


array([1, 1], dtype=int64)

In [32]:
#Menambah, menghapus, dan mengurutkan elemen
#Bagian ini mencakup np.sort(), np.concatenate()
#Mengurutkan elemen itu mudah dengan np.sort(). Anda dapat menentukan sumbu, jenis, dan urutan
# saat memanggil fungsi.

arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)



array([1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
# menggabungkan elemen
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [40]:
# Bagaimana cara mengetahui bentuk dan ukuran array?
# Bagian ini mencakup ndarray.ndim, ndarray.size, ndarray.shape

#contoh:
array_example = np.array([[[0, 1, 2, 3], [4, 5, 6, 7]],
                          [[0, 1, 2, 3], [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],[4, 5, 6, 7]]])

#Untuk mencari jumlah dimensi array, jalankan:
print(array_example.ndim)

# Untuk menemukan jumlah total elemen dalam array, jalankan:
print(array_example.size)

# Dan untuk menemukan bentuk array Anda, jalankan:
print(array_example.shape)



3
24
(3, 2, 4)


In [43]:
# Membentuk ulang Array
# Bagian ini mencakup arr.reshape()

a = np.arange(6)
print(a)
# Anda dapat menggunakan reshape() untuk membentuk ulang array Anda. Misalnya, Anda bisa membentuk ulang larik
# ini menjadi larik dengan tiga baris dan dua kolom:
b = a.reshape(3, 2)
print(b)

# Dengan np.reshape, Anda dapat menentukan beberapa parameter opsional:
np.reshape(a, newshape=(1, 6), order='C')

#a adalah array yang akan dibentuk ulang.


[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


array([[0, 1, 2, 3, 4, 5]])

In [62]:
#Cara mengubah array 1D menjadi array 2D (cara
# menambahkan sumbu baru ke array)
#Bagian ini mencakup np.newaxis, np.expand_dims

a1 = np.array([1, 2, 3, 4, 5, 6])
print(a1.shape)

# Anda dapat menggunakan np.newaxis untuk menambahkan sumbu baru:
a2 = a1[np.newaxis, :]
print(a2.shape)

# Anda dapat secara eksplisit mengonversi array 1D dengan vektor baris atau vektor kolom menggunakan
# np.newaxis. Misalnya, Anda dapat mengonversi array 1D menjadi vektor baris dengan menyisipkan sumbu
# di sepanjang dimensi pertama:

row_vector = a1[np.newaxis, :]
print(row_vector.shape)

# Atau, untuk vektor kolom, Anda bisa menyisipkan sumbu sepanjang dimensi kedua:

col_vector = a1[:, np.newaxis]
print(col_vector.shape)

# Anda juga dapat memperluas array dengan menyisipkan sumbu baru pada posisi tertentu
# dengan np.expand_dims.

a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)

# Anda dapat menggunakan np.expand_dims untuk menambahkan sumbu pada posisi indeks 1 dengan:
b = np.expand_dims(a, axis=1)
print(b.shape)

# Anda dapat menambahkan sumbu pada posisi indeks 0 dengan:
c = np.expand_dims(a, axis=0)
print(c.shape)

# Mengindeks dan mengiris
# Anda dapat mengindeks dan mengiris array NumPy dengan cara yang sama seperti Anda mengiris daftar Python.

data = np.array([1, 2, 3])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

# Jika Anda ingin memilih nilai dari array yang memenuhi kondisi tertentu, caranya mudah dengan NumPy.
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Anda dapat dengan mudah mencetak semua nilai dalam array yang kurang dari 5.
print(a[a < 5])

# Anda juga dapat memilih, misalnya, angka yang sama dengan atau lebih besar dari 5, dan menggunakan kondisi
# tersebut untuk mengindeks array
five_up = (a >= 5)
print(a[five_up])

# Anda dapat memilih elemen yang habis dibagi 2:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

# Atau Anda dapat memilih elemen yang memenuhi dua kondisi menggunakan & dan | operator:
c = a[(a > 2) & (a < 11)]
print(c)

# Anda juga dapat menggunakan operator logika & dan | untuk mengembalikan nilai boolean yang menentukan
# apakah nilai dalam array memenuhi kondisi tertentu atau tidak. Ini bisa berguna dengan array yang berisi
# nama atau nilai kategorikal lainnya.

five_up = (a > 5) | (a == 5)
print(five_up)


# Anda juga dapat menggunakan np.nonzero() untuk memilih elemen atau indeks dari array.
a3 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
# Anda dapat menggunakan np.nonzero() untuk mencetak indeks elemen yang, misalnya, kurang dari 5:
b3 = np.nonzero(a < 5)
print(b3)

# Jika Anda ingin membuat daftar koordinat tempat elemen berada, Anda dapat meng-zip array,
# mengulangi daftar koordinat, dan mencetaknya. Misalnya:
list_of_coordinates= list(zip(b3[0], b3[1]))
for coord in list_of_coordinates:
  print(coord)

# Anda juga dapat menggunakan np.nonzero() untuk mencetak elemen dalam array yang kurang dari 5 dengan:
print(a3[b3])

# Jika elemen yang Anda cari tidak ada dalam array, maka array indeks yang dikembalikan akan
# kosong. Misalnya:
not_there = np.nonzero(a3 == 42)
print(not_there)



(6,)
(1, 6)
(1, 6)
(6, 1)
(6,)
(6, 1)
(1, 6)
2
[1 2]
[2 3]
[2 3]
[1 2 3 4]
[ 5  6  7  8  9 10 11 12]
[ 2  4  6  8 10 12]
[ 3  4  5  6  7  8  9 10]
[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))
(0, 0)
(0, 1)
(0, 2)
(0, 3)
[1 2 3 4]
(array([], dtype=int64), array([], dtype=int64))


In [65]:
# Cara membuat array dari data yang ada
# Bagian ini mencakup pemotongan dan pengindeksan, np.vstack(), np.hstack(), np.hsplit(), .view(),
# copy()

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Anda dapat membuat array baru dari suatu bagian array kapan saja dengan menentukan di mana
# Anda ingin mengiris array Anda.

arr1 = a[3:8]
print(arr1)

# Anda juga dapat menumpuk dua array yang ada, baik secara vertikal maupun horizontal. Katakanlah Anda memiliki
# dua array, a1 dan a2:

a1 = np.array([[1, 1], 
               [2, 2]])
a2 = np.array([[3, 3], 
               [4, 4]])

# Anda dapat menumpuknya secara vertikal dengan vstack:
print(np.vstack((a1, a2)))

# Atau susun secara horizontal dengan hstack:
print(np.hstack((a1, a2)))


# Anda dapat menentukan jumlah array berbentuk sama yang akan dikembalikan atau kolom setelah pembagian
# terjadi.
x = np.arange(1, 25).reshape(2, 12)
print(x)

# Jika Anda ingin membagi array ini menjadi tiga array yang bentuknya sama, jalankan:
print(np.hsplit(x, 3))

# Jika Anda ingin membagi array setelah kolom ketiga dan keempat, jalankan:
print(np.hsplit(x, (3, 4)))




[4 5 6 7 8]
[[1 1]
 [2 2]
 [3 3]
 [4 4]]
[[1 1 3 3]
 [2 2 4 4]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
[array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]]), array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]]), array([[ 9, 10, 11, 12],
       [21, 22, 23, 24]])]
[array([[ 1,  2,  3],
       [13, 14, 15]]), array([[ 4],
       [16]]), array([[ 5,  6,  7,  8,  9, 10, 11, 12],
       [17, 18, 19, 20, 21, 22, 23, 24]])]


In [68]:
# Anda dapat menggunakan metode view untuk membuat objek array baru yang terlihat pada data yang sama
# dengan array asli ( salinan dangkal).

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Sekarang kita membuat array b1 dengan mengiris a dan memodifikasi elemen pertama b1. Ini juga akan mengubah
# elemen terkait di a !

b1 = a[0, :]
print(b1)

b1[0] = 99
print(b1)
print(a)

# Menggunakan metode copy akan membuat salinan lengkap dari array dan datanya ( salinan dalam). Untuk
# menggunakan ini pada array Anda, Anda bisa menjalankan:

b2 = a.copy()
print(b2)

[1 2 3 4]
[99  2  3  4]
[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [77]:
# Operasi array dasar
# Bagian ini mencakup penjumlahan, pengurangan, perkalian, pembagian, dan lainnya

# Anda dapat menambahkan array bersama dengan tanda plus.

data = np.array([1, 2])
ones = np.ones(2, dtype=int)
print(data + ones)

# Tentu saja, Anda dapat melakukan lebih dari sekadar penambahan!
print(data-ones)

print(data*data)

print(data/data) 

# Pengoperasian dasar sederhana dengan NumPy. Jika Anda ingin mencari jumlah elemen dalam array, Anda akan
# menggunakan sum(). Ini berfungsi untuk array 1D, array 2D, dan array dalam dimensi yang lebih tinggi.

a = np.array([1, 2, 3, 4])
print(a.sum())

# Untuk menambahkan baris atau kolom dalam array 2D, Anda harus menentukan sumbunya.
b = np.array([[1, 1], [2, 2]])

# Anda dapat menjumlahkan sumbu baris dengan:
print(b.sum(axis=0))

# Anda dapat menjumlahkan sumbu kolom dengan:
print(b.sum(axis=1))



[2 3]
[0 1]
[1 4]
[1. 1.]
10
[3 3]
[2 4]


In [78]:
# Penyiaran
# Ada kalanya Anda mungkin ingin melakukan operasi antara array dan satu bilangan (disebut juga operasi antara vektor
# dan skalar) atau antara array dengan dua ukuran berbeda. Misalnya, array Anda (kita akan sebut saja "data")
# mungkin berisi informasi tentang jarak dalam mil tetapi Anda ingin mengonversi informasi tersebut menjadi kilometer.
# Anda dapat melakukan operasi ini dengan:

data = np.array([1.0, 2.0])
print(data * 1.6)




[1.6 3.2]


In [82]:
# Operasi array yang lebih berguna
# Bagian ini mencakup maksimum, minimum, jumlah, mean, produk, deviasi standar, dan banyak lagi

# min,max,sum
print(data.max())

print(data.min())

print(data.sum())

a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
               [0.54627315, 0.05093587, 0.40067661, 0.55645993],
               [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

# Sangat umum untuk ingin menggabungkan sepanjang baris atau kolom. Secara default, setiap fungsi
# agregasi NumPy akan mengembalikan agregat seluruh array. Untuk menemukan jumlah atau jumlah
# minimum elemen dalam array Anda, jalankan:

print(a.sum())
print(a.min())
print(a.max(axis=0))

2.0
1.0
3.0
4.8595784
0.05093587
[0.54627315 0.82485143 0.40067661 0.56917101]
